on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: windows-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: 198.38.92.241
        username: ebbystephen
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: 'shoppinglist.meebbydeals.com/wwwroot/'