name : Shell Commands

on : [push]

jobs:
  run-shell-command:
    runs-on: windows-2016
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v